use PuntoDeVenta
go

IF NOT EXISTS (SELECT * FROM sysobjects WHERE type = 'U' AND name = 'TBL_RESTAURANTE_MESAS')
BEGIN
create table 
	TBL_RESTAURANTE_MESAS
	
	(
		ID_MESA BIGINT IDENTITY, 
		NUM_MESA INT,
		NOMBRE_MESA varchar(max),
		RESERVADA BIT,
		FECHA_ALTA DATETIME,
		HORA_ASIGNACION DATETIME,
		TOTAL_CUENTA MONEY,
		ASIGNADA BIT
	)
end

IF NOT EXISTS (SELECT * FROM sysobjects WHERE type = 'U' AND name = 'TBL_RESTAURANTE_PRODUCTOS')
BEGIN
create table 
	TBL_RESTAURANTE_PRODUCTOS
	
	(
		ID_PRODUCTO BIGINT IDENTITY, 
		CODIGO BIGINT,
		NOMBRE_PRODUCTO varchar(max),
		DESCRIPCION_PRODUCTO varchar(max),
		FECHA_ALTA DATETIME,		
		PRECIO MONEY,
		ACTIVO BIT
	)
end

IF NOT EXISTS (SELECT * FROM sysobjects WHERE type = 'U' AND name = 'TBL_RESTAURANTE_MESAS_PRODUCTOS')
BEGIN
create table 
	TBL_RESTAURANTE_MESAS_PRODUCTOS
	
	(
		ID_MESA_PRODUCTO BIGINT IDENTITY, 
		NUM_MESA INT,
		CODIGO_PRODUCTO BIGINT,
		PRECIO_PRODUCTO MONEY,
		FECHA_ALTA DATETIME,		
		PAGADO BIT
	)
end

--drop table TBL_RESTAURANTE_MESAS_PRODUCTOS