use PuntoDeVenta
go

IF NOT EXISTS (SELECT * FROM sysobjects WHERE type = 'U' AND name = 'TBL_RESTAURANTE_MESAS')
BEGIN
create table 
	TBL_RESTAURANTE_MESAS
	
	(
		ID_MESA BIGINT IDENTITY, 
		NUM_MESA INT,
		NOMBRE_MESA varchar(max),
		RESERVADA BIT,
		FECHA_ALTA DATETIME,
		HORA_ASIGNACION DATETIME,
		TOTAL_CUENTA MONEY,
		ASIGNADA BIT
	)
end

IF NOT EXISTS (SELECT * FROM sysobjects WHERE type = 'U' AND name = 'TBL_RESTAURANTE_PRODUCTOS')
BEGIN
create table 
	TBL_RESTAURANTE_PRODUCTOS
	
	(
		ID_PRODUCTO BIGINT IDENTITY, 
		CODIGO BIGINT,
		NOMBRE_PRODUCTO varchar(max),
		DESCRIPCION_PRODUCTO varchar(max),
		FECHA_ALTA DATETIME,		
		PRECIO MONEY,
		ACTIVO BIT
	)
end


/*
IF NOT EXISTS (SELECT * FROM sysobjects WHERE type = 'U' AND name = 'CAT_RESTAURANTE_TOTAL_MESAS')
BEGIN
create table 
	CAT_RESTAURANTE_TOTAL_MESAS
	(
		ID_TOTAL_MESAS BIGINT IDENTITY, 
		TOTAL_MESAS INT,
		MESAS_DISPONIBLES INT,
		MESAS_RESERVADAS INT
		
	)
end
*/

--DROP Table TBL_RESTAURANTE_MESAS
--drop table TBL_RESTAURANTE_PRODUCTOS