use PuntoDeVenta
go

insert into PuntoDeVenta..TBL_RESTAURANTE_MESAS(NUM_MESA,NOMBRE_MESA, RESERVADA,FECHA_ALTA,HORA_ASIGNACION,TOTAL_CUENTA,ASIGNADA)
values (1,'mesa1',0,GETDATE(),GETDATE(), 200, 1)

insert into PuntoDeVenta..TBL_RESTAURANTE_MESAS(NUM_MESA,NOMBRE_MESA, RESERVADA,FECHA_ALTA,HORA_ASIGNACION,TOTAL_CUENTA,ASIGNADA)
values (2,'mesa2',0,GETDATE(),GETDATE(), 0, 0)

insert into PuntoDeVenta..TBL_RESTAURANTE_MESAS(NUM_MESA,NOMBRE_MESA, RESERVADA,FECHA_ALTA,TOTAL_CUENTA,ASIGNADA)
values (3,'mesa3',0,GETDATE(), 400, 1)


exec SP_RESTAURANTE_AGREGAR_MESA 5, 'Mesa5'


begin tran
	exec SP_RESTAURANTE_AGREGAR_MESA @numMesa=1,@nombreMesa=N'Mesa1'
rollback tran

--update TBL_RESTAURANTE_MESAS set activa = 1


insert into TBL_RESTAURANTE_PRODUCTOS(CODIGO, NOMBRE_PRODUCTO, DESCRIPCION_PRODUCTO, FECHA_ALTA, PRECIO, ACTIVO)
values(110211, 'COCA-COLA', 'REFRESCO COCACOLA 600ML', GETDATE(), 14, 1)


insert into TBL_RESTAURANTE_PRODUCTOS(CODIGO, NOMBRE_PRODUCTO, DESCRIPCION_PRODUCTO, FECHA_ALTA, PRECIO, ACTIVO)
values(110212, 'CERVEZA MODELO', 'CERVEZA MODELO 500ML', GETDATE(), 20, 1)

exec SP_RESTAURANTE_OBTENER_PRODUCTOS '500'